# Generated by Django 4.2.5 on 2023-09-24 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paymentStatus',
            new_name='payment_status',
        ),
    ]
