# Generated by Django 4.2.5 on 2023-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_paymentstatus_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
